Final Project/FightingGame/config/routes.rb
Rails.application.routes.draw do
  resources :heros, only: [:new, :create, :edit, :update, :destroy]
  get 'heros/:id', to: redirect('/')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"
  get 'battle', to: 'heros#battle'
  post 'battle', to: 'heros#attack'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Final Project/FightingGame/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Final Project/FightingGame/app/models/hero.rb
class Hero < ApplicationRecord
  def sum_greater_than_300
     if atk + hp + defense + hp > 300
       errors.add(:base, 'Your stats cannot add to a number greater than 300')
     end
  end

  belongs_to :user
  validates :name, presence: true
  validates :kind, presence: true
  validates :hp, presence: true
  validates :defense, presence: true
  validates :atk, presence: true
  validates :speed, presence: true
  validates :hp, numericality: true
  validates :defense, numericality: true
  validates :atk, numericality: true
  validates :speed, numericality: true

  validate :sum_greater_than_300
end

Final Project/FightingGame/app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  has_many :heros #rails spelled it this way so I have to use it
end

Final Project/FightingGame/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

Final Project/FightingGame/app/controllers/heros_controller.rb
def hit(attacker, receiver, hp)
  if attacker[0] == nil
    damage = attacker.atk.to_f * (1 - (receiver[3].to_f)/600)
  else
    damage = attacker[2].to_f * (1 - (receiver.defense.to_f)/600)
  end
  damage = damage.round
  if hp - damage < 0
    return 0
  else
    return hp - damage
  end
end

class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
    @hero.user_id = current_user.id
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    params.permit!
    @hero = Hero.new(params[:hero])
    respond_to do |format|
      if @hero.save
        @hero.hp += 100
        if @hero.kind == "Elf"
          @hero.speed += 12
        elsif @hero.kind == "Human"
          @hero.atk += 3
          @hero.defense += 3
          @hero.hp += 15
          @hero.speed += 3
        elsif @hero.kind == "Troll"
          @hero.defense += 12
        elsif @hero.kind == "Giant"
          @hero.hp += 60
        elsif @hero.kind == "Barbarian"
          @hero.atk += 12
        end
        if @hero.save(validate: false)
          format.html { redirect_to "/", notice: 'Hero was successfully created.' }
          format.json { render :show, status: :created, location: @hero }
        end
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    params.permit!
    respond_to do |format|
      if @hero.update(params[:hero])
        @hero.hp += 100
        if @hero.kind == "Elf"
          @hero.speed += 12
        elsif @hero.kind == "Human"
          @hero.atk += 3
          @hero.defense += 3
          @hero.hp += 15
          @hero.speed += 3
        elsif @hero.kind == "Troll"
          @hero.defense += 12
        elsif @hero.kind == "Giant"
          @hero.hp += 60
        elsif @hero.kind == "Barbarian"
          @hero.atk += 12
        end
        if @hero.save(validate: false)
          format.html { redirect_to "/", notice: 'Hero was successfully updated.' }
          format.json { render :show, status: :ok, location: @hero }
        end
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /battle
  def battle
    @enemynum = rand(3)
  end

  # POST /battle
  def attack
    params.permit!
    @enemynum = params[:enemynum].to_i
    enemies = [["Bat", 100, 150, 50, 90, "https://i.pinimg.com/originals/b6/2b/d6/b62bd653a5ea86726d1b28b9cfc9916d.gif"],
    ["Zombie", 200, 50, 140, 10, "https://vignette.wikia.nocookie.net/plantsvszombies/images/a/af/Bbzzzzz.png/revision/latest?cb=20150924172130"],
    ["Ghost", 150, 100, 0, 150, "https://i.pinimg.com/originals/9d/e6/a7/9de6a7134d2a314489866b2561299488.png"]]
    enemy = enemies[@enemynum]
    hero = current_user.heros[0]
    enemyhp = enemy[1]
    herohp = hero.hp
    # Enemy attrs: "Name", hp, atk, def, speed, "url"
    if hero.speed > enemy[4]
      enemyhp = hit(hero, enemy, enemyhp)
      render plain: "Hero attacks first and enemy hp will be #{enemy[3]/600}"
    else
      herohp = hit(enemy, hero, herohp)
      render plain: "#{enemy[0]} attacks first and hero hp will be #{herohp}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:name, :atk, :hp, :def, :speed, :type, :user_id)
    end
end

Final Project/FightingGame/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if current_user
      @heros = current_user.heros.all
    end
  end
end

Final Project/FightingGame/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

Final Project/FightingGame/app/helpers/application_helper.rb
module ApplicationHelper
end

Final Project/FightingGame/app/helpers/heros_helper.rb
module HerosHelper
end

Final Project/FightingGame/app/helpers/home_helper.rb
module HomeHelper
end

Final Project/FightingGame/app/helpers/sessions_helper.rb
module SessionsHelper
end

Final Project/FightingGame/app/helpers/users_helper.rb
module UsersHelper
end

Final Project/FightingGame/app/views/heros/_form.html.erb
<%= form_with(model: hero, local: true) do |form| %>
  <% if hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
      <% hero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :hero_name %>
  </div>

  <div class="field">
    <%= form.label :atk %>
    <%= form.number_field :atk, id: :hero_atk %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.number_field :hp, id: :hero_hp %>
  </div>

  <div class="field">
    <%= form.label :def %>
    <%= form.number_field :def, id: :hero_def %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed, id: :hero_speed %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :hero_type %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :hero_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Final Project/FightingGame/app/views/heros/battle.html.erb
<script>
function attack(log, hero, enemy) {
  return "herro";
}
</script>

<%
images = ["https://forums.terraria.org/index.php?attachments/elite-knight-png.27964/",
  "http://2.bp.blogspot.com/-W5YWFyaZXl0/U_4xPYwNR8I/AAAAAAAAFr8/8Cl2ZJO4kH0/s1600/linknintendo.png",
  "https://lh3.googleusercontent.com/-IWJ1ZzWYJJw/VVGIZlYeoeI/AAAAAAACRdw/4MRUWtjv77s/w256-h256/8bit_human_male_Barbarian_long_sword.gif",
  "http://1.bp.blogspot.com/-bVEhlOCp48I/VYMCTw-xISI/AAAAAAAAP-4/f_LSmA8PT98/s640/clash-of-clans-giant-pixel-art.png",
  "http://streak.club/img/dXBsb2Fkcy9pbWFnZS8yMjk2LmdpZg==/original/5bcuaa.gif"]
imgnum = 0
if current_user.heros[0].kind == "Human"
  imgnum = 0
elsif current_user.heros[0].kind == "Elf"
  imgnum = 1
elsif current_user.heros[0].kind == "Barbarian"
  imgnum = 2
elsif current_user.heros[0].kind == "Giant"
  imgnum = 3
elsif current_user.heros[0].kind == "Troll"
  imgnum = 4
end
# "Name", hp, atk, def, speed, url
enemies = [["Bat", 100, 150, 50, 90, "https://i.pinimg.com/originals/b6/2b/d6/b62bd653a5ea86726d1b28b9cfc9916d.gif"],
["Zombie", 200, 50, 140, 10, "https://vignette.wikia.nocookie.net/plantsvszombies/images/a/af/Bbzzzzz.png/revision/latest?cb=20150924172130"],
["Ghost", 150, 100, 0, 150, "https://i.pinimg.com/originals/9d/e6/a7/9de6a7134d2a314489866b2561299488.png"]]
%>
<%= link_to "Back", "/" %>
<br>
<br>
<img height="200px" src="<%= images[imgnum] %>"></img>
<img height="200px" src="<%= enemies[@enemynum][5] %>" style="float: right;"></img>
<br>
<p style="text-align: center;">VS</p>
<b><%= current_user.heros[0].name %></b> <b style="float: right;"><%= enemies[@enemynum][0] %></b> <br>
<span>Health: <%= current_user.heros[0].hp %></span> <span style="float: right;">Health: <%= enemies[@enemynum][1] %></span> <br>
<span>Attack: <%= current_user.heros[0].atk %></span> <span style="float: right;">Attack: <%= enemies[@enemynum][2] %></span> <br>
<span>Defense: <%= current_user.heros[0].defense %></span> <span style="float: right;">Defense: <%= enemies[@enemynum][3] %></span> <br>
<span>Speed: <%= current_user.heros[0].speed %></span> <span style="float: right;">Speed: <%= enemies[@enemynum][4] %></span> <br>
<br>
<%= button_to "Attack!", :enemynum => @enemynum %>
<br>
<h2>Battle Log</h2>
<p id="notice"><%= notice %></p>

Final Project/FightingGame/app/views/heros/edit.html.erb
<h1>Editing Hero</h1>

<ul>
  <% for message in @hero.errors.full_messages %>
  <font color="red"><li><%= message %></li></font>
  <% end %>
</ul>

<%= form_for(@hero) do |form| %>
  <p>
      <%= form.label(:name) %><br>
      <%= form.text_field(:name) %><br>
    </p>
    <br>
    <h2>Stats</h2>
    <h6>The sum of your hero's attack, defense, speed, and added health must be less than or equal to 300 (You will have to subtract 100 from your added health and you will have to subtract your class bonus. Do not worry, they will still be added.)</h6>
    <p>
      <%= form.label(:attack) %><br>
      <%= form.number_field(:atk, min: 0, max: 300) %><br>
    </p>
    <p>
      <%= form.label(:health) %><br>
      100 + <%= form.number_field(:hp, min: 0, max: 300) %><br>
    </p>
    <p>
      <%= form.label(:defense) %><br>
      <%= form.number_field(:defense, min: 0, max: 300) %><br>
    </p>
    <p>
      <%= form.label(:speed) %><br>
      <%= form.number_field(:speed, min: 0, max: 300) %><br>
    </p>
    <p>
      <%= form.label(:class) %><br>
      <%= form.select(:kind, "<option>Elf</option><option>Human</option><option>Troll</option><option>Giant</option><option>Barbarian</option>".html_safe) %><br>
      Benefits from each class: <br>
      Elf: Speed + 12 <br>
      Troll: Defense + 12 <br>
      Barbarian: Attack + 12 <br>
      Giant: Health + 60 <br>
      Human: Attack + 3, Speed + 3, Defense + 3, Health + 15 <br>
    </p>
    <%= form.hidden_field(:user_id) %>
    <%= form.submit("Update Hero") %>
<% end %>
<br>
<%= link_to 'Back', "/" %>

Final Project/FightingGame/app/views/heros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Heros</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Atk</th>
      <th>Hp</th>
      <th>Def</th>
      <th>Speed</th>
      <th>Class</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.name %></td>
        <td><%= hero.atk %></td>
        <td><%= hero.hp %></td>
        <td><%= hero.defense %></td>
        <td><%= hero.speed %></td>
        <td><%= hero.kind %></td>
        <td><%= hero.user.name %></td>
        <td><%= link_to 'Show', hero %></td>
        <td><%= link_to 'Edit', edit_hero_path(hero) %></td>
        <td><%= link_to 'Destroy', hero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hero', new_hero_path %>

Final Project/FightingGame/app/views/heros/new.html.erb
<h1>New Hero</h1>

<ul>
  <% for message in @hero.errors.full_messages %>
  <font color="red"><li><%= message %></li></font>
  <% end %>
</ul>

<%= form_for(@hero) do |form| %>
  <p>
      <%= form.label(:name) %><br>
      <%= form.text_field(:name) %><br>
    </p>
    <br>
    <h2>Stats</h2>
    <h6>The sum of your hero's attack, defense, speed, and added health must be less than or equal to 300</h6>
    <p>
      <%= form.label(:attack) %><br>
      <%= form.number_field(:atk, min: 0, max: 300) %><br>
    </p>
    <p>
      <%= form.label(:health) %><br>
      100 + <%= form.number_field(:hp, min: 0, max: 300) %><br>
    </p>
    <p>
      <%= form.label(:defense) %><br>
      <%= form.number_field(:defense, min: 0, max: 300) %><br>
    </p>
    <p>
      <%= form.label(:speed) %><br>
      <%= form.number_field(:speed, min: 0, max: 300) %><br>
    </p>
    <p>
      <%= form.label(:class) %><br>
      <%= form.select(:kind, "<option>Elf</option><option>Human</option><option>Troll</option><option>Giant</option><option>Barbarian</option>".html_safe) %><br>
      Benefits from each class: <br>
      Elf: Speed + 12 <br>
      Troll: Defense + 12 <br>
      Barbarian: Attack + 12 <br>
      Giant: Health + 60 <br>
      Human: Attack + 3, Speed + 3, Defense + 3, Health + 15 <br>
    </p>
    <%= form.hidden_field(:user_id) %>
    <%= form.submit("Create Hero") %>
<% end %>

<br>

<%= link_to 'Back', heros_path %>

Final Project/FightingGame/app/views/heros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hero.name %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @hero.atk %>
</p>

<p>
  <strong>Health:</strong>
  <%= @hero.hp %>
</p>

<p>
  <strong>Defense:</strong>
  <%= @hero.defense %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @hero.speed %>
</p>

<p>
  <strong>Class:</strong>
  <%= @hero.kind %>
</p>

<p>
  <strong>User:</strong>
  <%= @hero.user.name %>
</p>

<%= link_to 'Edit', edit_hero_path(@hero) %> |
<%= link_to 'Back', heros_path %>

Final Project/FightingGame/app/views/home/show.html.erb
<% if current_user %>
  <h1>Home</h1>
  <% if current_user.heros.size == 0 %>
    You do not currently have a hero.
    <br>
    <%= link_to "Create Hero", new_hero_path %>
  <% else %>
    Your hero:
    <br>
    <%
    images = ["https://forums.terraria.org/index.php?attachments/elite-knight-png.27964/",
      "http://2.bp.blogspot.com/-W5YWFyaZXl0/U_4xPYwNR8I/AAAAAAAAFr8/8Cl2ZJO4kH0/s1600/linknintendo.png",
      "https://lh3.googleusercontent.com/-IWJ1ZzWYJJw/VVGIZlYeoeI/AAAAAAACRdw/4MRUWtjv77s/w256-h256/8bit_human_male_Barbarian_long_sword.gif",
      "http://1.bp.blogspot.com/-bVEhlOCp48I/VYMCTw-xISI/AAAAAAAAP-4/f_LSmA8PT98/s640/clash-of-clans-giant-pixel-art.png",
      "http://streak.club/img/dXBsb2Fkcy9pbWFnZS8yMjk2LmdpZg==/original/5bcuaa.gif"]
    imgnum = 0
    if current_user.heros[0].kind == "Human"
      imgnum = 0
    elsif current_user.heros[0].kind == "Elf"
      imgnum = 1
    elsif current_user.heros[0].kind == "Barbarian"
      imgnum = 2
    elsif current_user.heros[0].kind == "Giant"
      imgnum = 3
    elsif current_user.heros[0].kind == "Troll"
      imgnum = 4
    end
    %>
    <img style="float: right; margin-right: 50%; height: 200px" src="<%= images[imgnum] %>"></img>
    <% hero = current_user.heros[0] %>
    <h3><%= hero.name %></h3> <br>
    Health: <%= hero.hp %> <br>
    Attack: <%= hero.atk %> <br>
    Defense: <%= hero.defense %> <br>
    Speed: <%= hero.speed %> <br>
    Class: <%= hero.kind %> <br>
    <%= link_to 'Edit', edit_hero_path(hero) %> |
    <%= link_to 'Delete Your Hero', hero, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
    <br>
    <%= link_to 'Battle!', '/battle'%>
  <% end %>
<% end %>

Final Project/FightingGame/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fighting Game</title>
    <link rel="icon" href="https://images.sftcdn.net/images/t_optimized,f_auto/p/5a93b3ee-96d7-11e6-8fdd-00163ed833e7/728637478/zelda-adventure-for-minecraft-logo.png" type="image/png">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div style="text-align:right;">
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
      <% end %>
    </div>
    <div>
      <% if current_user %>
        <%= yield %>
      <% else %>
        <a style="position:fixed; left: 50%; margin-left: -200px; top: 50%; margin-top: -49.735px;" id="sign_in" href="/auth/google_oauth2"><img src="http://www.setyourowntests.com/_/rsrc/1468869481521/help/accounts/btn_google_signin_dark_normal_web%402x.png" width="400"></img></a>
      <% end %>
    </div>
  </body>
</html>